Repository GroupBy-Side-Project-GSP/bridge-server, pull requests merged in 2022-02, with the labels that each got.

#4 🔀 :: (#3) CI 세팅
  .github/workflows/CI.yml
Labels: 프로젝트 설정

#6 🔀 :: (#5) Lint 설정
  .github/workflows/Build.yml
  .github/workflows/CI.yml
  .github/workflows/Init.yml
  build.gradle
Labels: 프로젝트 설정

#13 🔀 :: (#12) company 엔티티 추가
  build.gradle
  src/main/java/com/gsp/bridge/domain/company/domain/Company.java
  src/main/java/com/gsp/bridge/domain/company/domain/repository/CompanyRepository.java
  src/main/java/com/gsp/bridge/domain/company/presentation/dto/reqeust/.gitkeep
  src/main/java/com/gsp/bridge/domain/company/presentation/dto/response/.gitkeep
  src/main/java/com/gsp/bridge/domain/company/service/.gitkeep
  src/main/java/com/gsp/bridge/domain/user/domain/repository/.gitkeep
  src/main/java/com/gsp/bridge/domain/user/presentation/dto/reqeust/.gitkeep
  src/main/java/com/gsp/bridge/domain/user/presentation/dto/response/.gitkeep
  src/main/java/com/gsp/bridge/global/enums/Authority.java
  src/main/java/com/gsp/bridge/infrastructure/s3/DefaultImage.java
  src/main/resources/application.yml
Labels: 기능 추가

#17 🔀 :: (#14) Notice 엔티티
  src/main/java/com/gsp/bridge/domain/notice/domain/Notice.java
  src/main/java/com/gsp/bridge/domain/notice/domain/repository/NoticeRepository.java
Labels: 기능 추가

#19 🔀 :: (#18) company 엔티티 리팩토링
  src/main/java/com/gsp/bridge/domain/company/domain/Company.java
Labels: 리팩토링

#20 🔀 :: (#15) Schedule 엔티티 생성
  src/main/java/com/gsp/bridge/domain/schedule/domain/Schedule.java
  src/main/java/com/gsp/bridge/domain/schedule/domain/repostiory/ScheduleRepository.java
Labels: 기능 추가

#28 🔀 :: (#25) BusinessCategory 엔티티
  src/main/java/com/gsp/bridge/domain/businesscategory/domain/BusinessCategory.java
  src/main/java/com/gsp/bridge/domain/businesscategory/domain/repository/BusinessCategoryRepository.java
Labels: 기능 추가

#30 🔀 :: (#29) Favorites 엔티티
  src/main/java/com/gsp/bridge/domain/favorites/domain/Favorites.java
  src/main/java/com/gsp/bridge/domain/favorites/domain/repository/FavoritesRepository.java
Labels: 기능 추가

#32 🔀 :: (#31) Report 엔티티
  src/main/java/com/gsp/bridge/domain/report/domain/Report.java
  src/main/java/com/gsp/bridge/domain/report/domain/repository/ReportRepository.java
Labels: 기능 추가

#34 🔀 :: (#33) WithdrawalReasonCategory 엔티티
  src/main/java/com/gsp/bridge/domain/withdrawalreasoncategory/domain/WithdrawalReasonCategory.java
  src/main/java/com/gsp/bridge/domain/withdrawalreasoncategory/domain/repository/WithdrawalReasonCategoryRepository.java
Labels: 기능 추가

#36 🔀 :: (#35) WithdrawalReason 엔티티
  src/main/java/com/gsp/bridge/domain/withdrawalreason/domain/WithdrawalReason.java
  src/main/java/com/gsp/bridge/domain/withdrawalreason/domain/repository/WithdrawalReasonRepository.java
Labels: 기능 추가
